<?php

/**
 * @file
 * Contains readmehelp.module.
 */

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements the ReadmeHelpMarkdownConverter service.
 *
 * If the module name is passed then README* file in the modules root
 * directory will be rendered. If the file path passed is a valid
 * directory within Drupal installation then the first README* file found on
 * the path will be rendered. If the file path is an absolute path to existing
 * Drupal site's file then this file will be rendered disregarding of the file
 * name or extension.
 *
 * @param string $module_name
 *   (optional) The module to look for the files.
 * @param string $file_path
 *   (optional) The alternative file path.
 *
 * @return \Drupal\readmehelp\ReadmeHelpMarkdownConverter|string
 *   The markdown converter service or markup generated for a file.
 */
function readmehelp_converter_service($module_name = NULL, $file_path = NULL) {
  $converter = \Drupal::service('readmehelp.markdown_converter');
  if ($module_name) {
    return $converter->convertMarkdownFile($module_name, $file_path);
  }

  return $converter;
}

/**
 * Implements hook_system_info_alter().
 */
function readmehelp_form_system_modules_alter(&$form, FormStateInterface $form_state, $form_id) {
  $readmehelp_modules = \Drupal::config('readmehelp.settings')
    ->get('readmehelp_modules');

  foreach ($form['modules'] as $package => $modules) {
    if (is_array($modules)) {
      foreach ($modules as $module => $data) {
        if (in_array($module, $readmehelp_modules)) {
          $help = t('README Help');
          $form['modules'][$package][$module]['links']['help'] = [
            '#type' => 'link',
            '#title' => $help,
            '#url' => Url::fromRoute('help.page', ['name' => $module]),
            '#options' => [
              'attributes' => [
                'class' => ['module-link', 'module-link-help'],
                'title' => $help,
              ],
            ],
          ];
        }
      }
    }
  }
}

/**
 * Implements hook_modules_installed().
 */
function readmehelp_modules_installed($modules, $is_syncing) {
  $readmehelp_modules = $hook_help = [];
  $module_handler = \Drupal::moduleHandler();

  $module_handler->invokeAllWith(
    'help',
    function (callable $hook, string $machine_name) use (&$hook_help) {
      $hook_help[$machine_name] = $machine_name;
    }
  );

  if (in_array('readmehelp', $modules)) {
    $modules = array_keys($module_handler->getModuleList());
  }

  foreach ($modules as $machine_name) {
    if (!isset($hook_help[$machine_name])) {
      $readmehelp_modules[] = $machine_name;
    }
  }

  if (empty($readmehelp_modules)) {
    return;
  }

  $config = \Drupal::configFactory()->getEditable('readmehelp.settings');
  $modules = $config->get('readmehelp_modules') ?? [];
  $readmehelp_modules = array_merge($modules, $readmehelp_modules);
  $config->set('readmehelp_modules', $readmehelp_modules)->save();
}
