<?php

/**
 * @file
 * Install, uninstall and update functions for the readmehelp module.
 */

use Drupal\filter\Entity\FilterFormat;

/**
 * Implements hook_uninstall().
 *
 * Disabling the 'readmehelp_markdown' filter does not remove it from format
 * available filters. Users may try to disable the format which allows to
 * uninstall the module but this removes it from the UI without any chance to
 * get it back. So, the clean up must be done on uninstall.
 *
 * @see https://www.drupal.org/project/drupal/issues/949220
 * @see https://www.drupal.org/project/drupal/issues/2502637
 */
function readmehelp_uninstall() {
  foreach (FilterFormat::loadMultiple() as $filter_format) {
    $filters = $filter_format->getPluginCollections()['filters'];
    if ($filters->has('readmehelp_markdown')) {
      $filters->removeInstanceId('readmehelp_markdown');
    }
  }
}

/**
 * Create readmehelp_settings config.
 */
function readmehelp_update_8201() {
  if (readmehelp_modules_installed(['readmehelp'], FALSE)) {
    return t('Added the README Help module settings.');
  }
  else {
    return t('Saving the README Help module settings has failed. Set them manually on the module configuration form.');
  }
}
