# Schema for the configuration files of the README Help module.
readmehelp.settings:
  type: config_object
  label: 'README Help settings'
  mapping:
    readmehelp_modules:
      type: sequence
      label: 'README Help modules'
      sequence:
        type: string
        label: 'README Help module'
